version: "3.9"

services:
  restfulapi:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8010:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    deploy:
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - type: tmpfs
        target: /data/db

networks:
  app-network:
    driver: bridge
