services:
  mongo:
    image: mongo:6.0
    volumes:
      - type: tmpfs
        target: /data/db
    network_mode: host
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    network_mode: host
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-data:/prometheus
      - ../config/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    network_mode: host

  restfulapi:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - JAEGER_ENDPOINT=grpc://jaeger:4317
    depends_on:
      - mongo
      - jaeger
      - prometheus
    deploy:
      restart_policy:
        condition: on-failure
    network_mode: host

volumes:
  prometheus-data:
